### ISSUE TITLE
pkg-config can't find mdbtools

### ISSUE THREAD

**Issue by tomcass240** [mdbtools/gmdb2#10]
It mentions in the readme that mdbtools needs to be installed where pkg-config can find it, but it doesn't mention where the default directories are or how to tell pkg-config to use different directories. I'd appreciate if anyone could tell me how I can configure pkg-config to find mdbtools.

I am using debian bullseye and installed mdbtools from the repository.

**Comment by evanmiller** [comment]
Try `env PKG_CONFIG_PATH=/path/to/lib/pkg-config ./configure`

**Comment by tomcass240** [comment]
Still giving me the error "configure: error: Could not find MDB Tools, which are required to build gmdb2"

I can't see libmdb in any of my pkgconfig folders, maybe that's why? I installed mdbtools from the debian repo.

**Comment by tomcass240** [comment]
Never mind actually, this software clearly isn't worth the hassle of trying to get it to function correctly.

**Comment by PixsaOJ** [comment]
Please reopen. this needs to be solved.

**Comment by PixsaOJ** [comment]
It has to do something with packages being replaced with `libmdb3` and `libmdbsql3`.
I tried renaming in configure script but no luck.

Using Ubuntu 21.10 (Pop OS)

**Comment by rhurlin** [comment]
Hi @PixsaOJ,
You did not tell us which version of `mdbtools` is installed and which version of `gmdb2` you want to install.

Could you also please tell us what output `pkg-config --libs --cflags libmdb` and `pkg-config --libs --cflags libmdbsql` provide?

**Comment by PixsaOJ** [comment]
`mdbtools` version:
```
mdbtools/impish,now 0.9.4-1ubuntu1 amd64 [installed]
odbc-mdbtools/impish,now 0.9.4-1ubuntu1 amd64 [installed]
```

There is no `libmdb` or `libmdbsql` package for me. 

Here are the outputs of my versions:
```bash

libmdb3 is already the newest version (0.9.4-1ubuntu1).
libmdbsql3 is already the newest version (0.9.4-1ubuntu1).


> pkg-config --libs --cflags libmdb
Package libmdb was not found in the pkg-config search path.
Perhaps you should add the directory containing `libmdb.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libmdb' found

> pkg-config --libs --cflags libmdb3
Package libmdb3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libmdb3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libmdb3' found


> pkg-config --libs --cflags libmdbsql
Package libmdbsql was not found in the pkg-config search path.
Perhaps you should add the directory containing `libmdbsql.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libmdbsql' found

>  pkg-config --libs --cflags libmdbsql3
Package libmdbsql3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libmdbsql3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libmdbsql3' found
```

This is weird, because `libmdb3` and `libmdbsql3` are installed.

I am trying to get latest `gmdb2` release installed.

**Comment by rhurlin** [comment]
No, pkg-config is looking here for `libmdb.pc` and `libmdbsql.pc`, not the libraries libmdb.so and libmdbsql.so. Both are configuration files and should be installed by mdbtools. On my box (FreeBSD) they are under `/usr/local/libdata/pkgconfig/`. These .pc files should help other installations (like gmdb2) to find, where mdbtools is installed.  You could try to find out manually, if and where `libmdb.pc` and `libmdbsql.pc` exist on your box.  If needed, use `man pkgconf` to get more info about pkg-config.

In the Github repo, there is a newer version [MDB Tools 1.0.0](https://github.com/mdbtools/mdbtools/releases/tag/v1.0.0) since Oct 25 2021. Don't know, if your version 0.9.4 does not include these configuration files. I am wondering, if your Ubuntu installation or your repo is somewhat outdated? But I am not a Linux expert, can't help here :(

[gmdb2 0.9.1](https://github.com/mdbtools/gmdb2/releases/tag/v0.9.1) is from Aug 25 2021, on FreeBSD it works quite nice with MDB Tools 1.0.0.

**Comment by PixsaOJ** [comment]
There is no `/usr/local/libdata` folder for me.

`sudo find / -name libmdbsql` gives me nothing.

From this [link](https://packages.ubuntu.com/hirsute/amd64/libmdb3/filelist), we can see what files are installed from my package. IDK if package-config generates its own files tho.

I am going to try MDB TOOLS 1.0.0 now.

**Comment by PixsaOJ** [comment]
### I have passed the libgdm part !
compiling `mdbtools 1.0.0` worked for this issue.

Now it requires `gtk+-3.0 >= 3.22` oh comeon. I am on Gnome 40.
`libgtk-3-0/impish,now 3.24.30-1ubuntu1 amd64 [installed,automatic]`
I do have libgtk-3-0 installed, what else does it want?

**Comment by rhurlin** [comment]
> There is no `/usr/local/libdata` folder for me.

Yes, this is FreeBSD specific and only an example ;)

> `sudo find / -name libmdbsql` gives me nothing.

No wonder, according to [filelist](https://packages.ubuntu.com/hirsute/amd64/libmdb3/filelist) nothing was installed either ;)

> From this [link](https://packages.ubuntu.com/hirsute/amd64/libmdb3/filelist), we can see what files are installed from my package. IDK if package-config generates its own files tho.

It looks like this Ubuntu package installs only the library, not the whole MDB Tools. No, pkg-config is needed in the gmdb2 configuration to have a look for the mdbtools .pc files. Both .pc files **should be installed by mdbtools** from `libmdb.pc.in` and `libmdbsql.pc.in`.

> compiling mdbtools 1.0.0 worked for this issue.

Nice to hear!

> I do have libgtk-3-0 installed, what else does it want?

Yes, gmdb2 has not yet been revised to the same extent as the MDB Tools. This should be made up for when the opportunity arises.

On my system (FreeBSD) the following dependencies are needed: pango, libxml2, gdk-pixbuf2, readline, glib2, gettext-runtime, atk2 and of course mdbtools itself.

**Comment by PixsaOJ** [comment]
Thanks for help @rhurlin . I am going to give up now. It would be nice to have dependency list so this kind of issues does not come up in future.
