### ISSUE TITLE
configure on standard Debian 10

### ISSUE THREAD

**Issue by kalpha2** [mdbtools/gmdb2#2]
So I am running Debian 10, using Deb repositories I have 

`sudo apt-get install mdbtools odbc-mdbtools unixodbc unixodbc-dev`

NB mdbtools is at version 0.7.1-6 and unixodbc at version 2.3.6

I then try 
`git clone https://github.com/mdbtools/gmdb2.git
cd gmdb2/
autoreconf -f -i -Wno-portability
./configure 
`
which results in
`checking for MDBTOOLS... no
checking for MDBSQL... no
configure: error: Could not find MDB Tools, which are required to build gmdb2.
`
Does it require mdbtools to be a certain version or is it struggling to find where Debian 10 has placed mdbtools?

Can I build gmdb2 if I  
`git clone https://github.com/mdbtools/mdbtools.git`
and do a make referencing it somehow (i.e. not do an install as such) ?

**Comment by evanmiller** [comment]
Hi, you have a couple of options:

The current GitHub version of gmdb2 requires MDB Tools 0.9.0 or later. To compile the latest gmdb2, you will need to remove Debian's mdbtools and install your own.

gmdb2 uses pkg-config to determine the package version. You can confirm that gmdb2 is finding the correct version with pkg-config

`pkg-config libmdb --modversion`

Your other option is to manually download and install mdbtools 0.7.1, which includes gmdb2. This is not really recommended as there have been a large number of security-related fixes included in mdbtools 0.9.

**Comment by kalpha2** [comment]
Thank you, am moving to Debian 11 will raise a new ticket for issues I have there
