### ISSUE TITLE
Ubuntu 20.04 build fails from deprecated declarations in gtk-2.0 and libgnome-2.0

### ISSUE THREAD

**Issue by boinkitsbroken** [mdbtools/gmdb2#4]
Make fails to build because of these errors. The include for `gnome.h` from `libgnomeui-2.0`, so far, is the offender. 'GTypeDebugFlags', 'GTimeVal', and 'GParameter' cause Werror flags for being deprecated, which GCC then chokes on and fails. GCC, supposedly, ignores these flags by default, so '-Werror=deprecated-declarations' is being deliberately set somewhere during ./configure.
I have not yet determined if the cause is in gmdb2 or somewhere in GNOME yet, but starting an Issue leading to a workaround seemed like a good idea.
Both `libgnomeui` and `gnome-doc-utils` (another hidden dependency it seems) are excluded from many current Debian distros. This may be from the push towards `gtk-3.0` and `Yelp-tools`. For now I am taking a snap approach: get ALL the files needed in one place in the build folder.  I am not a hardened programmer, so I can only hope it works.

**Comment by boinkitsbroken** [comment]
Tried `autoreconf -f -i -Wno-portability -Wno-obsolete` and got errors:
`make[2]: Entering directory '/home/broken/Projects/gmdb2/src/help'
/bin/bash: scrollkeeper-config: command not found
/bin/bash: line 1: scrollkeeper-config: command not found
The file '/Templates/C/scrollkeeper_cl.xml' does not exist.
Please check your ScrollKeeper installation.
`
That's it. I'm deleting /src/help. ScrollKeeper is older than my son who just graduated high school.

**Comment by boinkitsbroken** [comment]
Found a workaround:

1. Download and install `gnome-doc-utils` from an Ubuntu archive repository. I used this version from [here](http://archive.ubuntu.com/ubuntu/pool/universe/g/gnome-doc-utils/gnome-doc-utils_0.20.10-4_all.deb).
2. Install the .deb file via Software Install, `dpkg`, or your favorite method (if any).
3. Change Line 30 in `configure.ac` from `CFLAGS="$CFLAGS -Wall -Werror"` to: 
          `CFLAGS="$CFLAGS -Wno-all -Wno-error"`.
4. run `autoreconf -f -i -Wno-portability -Wno-obsolete`.
5. run `./configure --disable-scrollkeeper`.
6. run `make`.
7. run `sudo make install`.

GMDB2 will build and install just fine. Please add `gnome-doc-utils` to the list of dependencies in the README.md, along with a note to users that they need the `-dev` versions of `libglade-2.0` and `libgnomeui-2.0` before `pkg-config` will actually see those libraries. I also highly recommend eliminating any reference to ScrollKeeper from the source code.

This workaround works for me. Telling GCC to ignore all warnings may NOT be a very good way of making the build work, but it's what I found that worked.

**Comment by evanmiller** [comment]
Thanks for the notes. Although this is advertised as "beta" software, it's a legacy project with some ancient dependencies. I have updated the README with some of your suggestions. I'll need to investigate the warnings separately.

**Comment by rhurlin** [comment]
> Found a workaround:
> ...

@boinkitsbroken Thanks for this issue. I have similar problems in FreeBSD, for which I prepare a port gmdb2. FreeBSD has now completely separated from Python2 and with it all dependencies, as far as they could not be adapted to Python3.

libgnomeui and gnome-doc-utils are therefore no longer present. I am now looking for ways to make the gmdb2 functionality independent of these old dependencies. Resurrecting deprecated gnome-doc-utils is no option on FreeBSD :(

**Comment by evanmiller** [comment]
I've spent some time migrating the interface to GTK+3 – so the gmdb2 `main` branch should now compile on modern platforms. The only downside is that I've removed help files from the build, since none of the old tools are supported. I'll look into migrating the help documentation to Yelp later. In the meantime, try it out!

**Comment by evanmiller** [comment]
Quick update - I've migrated the old Gnome docs to Yelp. I don't actually have a system with Yelp installed, so I'd appreciate it if someone could try it out and see if it actually works. (Press F1 or choose Help > Help)

**Comment by evanmiller** [comment]
GMDB2 now builds on Ubuntu 20.04 (see Actions tab) with GTK3, so I'm closing this issue. Feel free to open a new issue if you run into any issues.

**Comment by lonix1** [comment]
@evanmiller I've looked at the actions tab but no sure what to search for.

Does anyone know how to build this on ubuntu 20.04?

Thanks!

**Comment by lonix1** [comment]
@evanmiller I've pieced together some build config from the `.github/workflows/build.yml` file, but it doesn't work for me.

In a clean ubuntu server 20.04 docker container:
````sh
apt install clang gcc-9 gcc-10
apt install make
apt install autoconf
apt install git

cd /tmp
git clone -b master https://github.com/mdbtools/mdbtools.git mdbtools
cd mdbtools

autoreconf -i -f     # errors here
./configure          # errors here
make                 # errors here
````

Anyone have a working build script?

**Comment by evanmiller** [comment]
What are the errors?

**Comment by lonix1** [comment]
No worries, I've since used the cli tool instead.

The errors - the build script failed. I don't think the above script is complete, it's missing dependencies but I couldn't figure out what they were.
