### ISSUE TITLE
Rename (or re-version) gmdb2?

### ISSUE THREAD

**Issue by evanmiller** [mdbtools/gmdb2#9]
With the recent GTK+3 port, the underlying graphical toolkit of this program is now an implementation detail, so the "g" doesn't really have to stand for GNOME any more. It's also rather confusing that this is version "2" since there was never really a version "1" (just lots of alphas included in the main mdbtools releases), and the only release here so far has been "0.9.0". Maybe others don't have this problem, but I also have to look twice when I see references to the [`gdbm`](https://www.gnu.org.ua/software/gdbm/) package.

Just wanted to open the discussion to see if others had opinions about renaming this project to something more descriptive, or changing or removing the `2` in the name, before the first official stable release occurs (will we call it 1.0? 2.0? 3.0?).

I do like that the `gmdb2` command-line name is nice and terse at 5 characters. I am also kind of lazy and don't feel like updating references to gmdb2 everywhere.

As a secondary matter: it would be nice to have a standard name for package maintainers. It looks like Debian used to carry the project as `mdbtools-gmdb`, and @rhurlin has recently packaged it up for FreeBSD as `gmdb2`. I'd like to have a cross-platform package name that we can move forward with. (I'm hoping to do MacPorts and homebrew packages once there's an updated Debian package that I can point to.)

Maybe the easiest solution is to jump straight to version 2.0 and call it done. The non-existent version 1 will be one of those ancient Unix mysteries like the unknown predecessor to bzip2.

The floor is open for discussion.

**Comment by rhurlin** [comment]
Hi @evanmiller,
Thanks for this discussion :)

> With the recent GTK+3 port, the underlying graphical toolkit of this program is now an implementation detail, so the "g" doesn't really have to stand for GNOME any more. It's also rather confusing that this is version "2" since there was never really a version "1" (just lots of alphas included in the main mdbtools releases), and the only release here so far has been "0.9.0". Maybe others don't have this problem, but I also have to look twice when I see references to the [`gdbm`](https://www.gnu.org.ua/software/gdbm/) package.

Wasn't the original meaning of the abbreviation GTK Gimp Toolkit instead of Gnome ...? So I was previously of the opinion that the leading G in GMDB stands either for the GTK or for GUI (and thus not for GNOME)?

> Just wanted to open the discussion to see if others had opinions about renaming this project to something more descriptive, or changing or removing the `2` in the name, before the first official stable release occurs (will we call it 1.0? 2.0? 3.0?).

I like the old name and would not mind if it stays ;)

Until now I was of the opinion that the number 2 has derived from GTK2. But the context doesn't really matter either.

> I do like that the `gmdb2` command-line name is nice and terse at 5 characters. I am also kind of lazy and don't feel like updating references to gmdb2 everywhere.

Me too.

> As a secondary matter: it would be nice to have a standard name for package maintainers. It looks like Debian used to carry the project as `mdbtools-gmdb`, and @rhurlin has recently packaged it up for FreeBSD as `gmdb2`. I'd like to have a cross-platform package name that we can move forward with. (I'm hoping to do MacPorts and homebrew packages once there's an updated Debian package that I can point to.)

On FreeBSD there is a convention that the naming of a port or package is derived directly from the naming of the Github source. Since the software is named gmdb2 on Github, I named the port after it.

If GMDB2 is renamed, the FreeBSD port can theoretically be renamed as well.

> Maybe the easiest solution is to jump straight to version 2.0 and call it done. The non-existent version 1 will be one of those ancient Unix mysteries like the unknown predecessor to bzip2.

As I understand it, the number 2 in the name of the software does not stand for the GMDB version, but points to the origin of the GTK2 version, see above.

If this is correct, then surely the running version number can be chosen completely independent of the naming GMDB2 ...?

> The floor is open for discussion.

Thank you for the opportunity to contribute my opinion.

**Comment by evanmiller** [comment]
These lines:

https://github.com/mdbtools/gmdb2/blob/f43250a96630038308fa21d24cc70b425b48dc31/src/main2.c#L76-L82

Indicate the "original G" was for GNOME. Doesn't really matter though – it can stand for GTK or Graphical now. We should probably update the above information before 1.0.

As you suspected, it also looks like the "2" was introduced during a port from GNOME / GTK 1 to GNOME / GTK2: https://github.com/mdbtools/gmdb2/commit/dbc9a1449ca927a48c71cc862e8cd33946c2f856

The remaining question would be whether to ship the next stable version as `gmdb`, `gmdb2`, or `gmdb3`. Since there's not really a reason to run old and new side-by-side, `gmdb2` would be the least disruptive. Although the number in the name doesn't have to match the software version number, I just think it will be a little weird in the future to have a "gmdb2 3.0" etc. (Mac OS X had this problem and dropped the X when they went to 11.0.)

I will note that the search term "gmdb" has quite a bit of competition as a Guaranteed Minimum Death Benefit, so maybe keeping the 2 around isn't such a bad idea.
